# Generated by Django 4.0.4 on 2022-05-30 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('summary', models.CharField(help_text='Enter a brief description of the course', max_length=256)),
                ('code', models.CharField(help_text='Enter the courses unique identifier code', max_length=16, unique=True)),
                ('level', models.CharField(choices=[('a', 'Advanced'), ('b', 'Beginner'), ('i', 'Intermediate')], default='b', max_length=1)),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.author')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter course topic, e.g. Django', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='CourseInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('finishes', models.DateField()),
                ('status', models.CharField(choices=[('a', 'Active'), ('p', 'Paused'), ('t', 'Terminated'), ('c', 'Completed')], default='a', max_length=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['finishes'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='topic',
            field=models.ManyToManyField(help_text='Select topics for this course', to='catalog.topic'),
        ),
    ]
